version: '3.8'

services:
  app:
    image: melquiadesrodrigues/php-compose:8.0.1-fpm-alpine3.13
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env.template:.env  ./.docker/app/entrypoint.sh
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "laravel"
      MYSQL_USERNAME: "root"
      MYSQL_PASSWORD: "12345"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    volumes:
      - .:/var/www
    networks:
      - app-newtork
    depends_on:
      - mysql
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/templates:/etc/nginx/templates
    environment:
      PHP_HOST: "app"
      PHP_PORT: "9000"
    networks:
      - app-newtork
    depends_on:
      - app

  mysql:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "33060:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_USER: 'root'
    networks:
      - app-newtork

  redis:
     image: redis:alpine
     container_name: redis
     expose:
       - 6379
     networks:
       - app-newtork

networks:
  app-newtork:
    driver: bridge
