version: '3.8'

services:
  app:
    image: melquiadesrodrigues/php-compose:8.0.6-fpm-alpine3.13
    container_name: micro-videos-app
    entrypoint: dockerize -template ./.docker/app/.env.template:.env -wait tcp://mysql:3306 -timeout 40s ./.docker/app/entrypoint.sh
    environment:
      _DB_HOST: "mysql"
      _DB_DATABASE: "code_micro_videos"
      _DB_USERNAME: "root"
      _DB_PASSWORD: "12345"
    #  XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9001 remote_enable=1 xdebug.remote_autostart=1 remote_handler=dbgp xdebug.remote_log=/var/log/xdebug.log
    ports:
      - "9001:9001"
    volumes:
      - .:/var/www
    networks:
      - codeflix-micro-videos
    depends_on:
      - mysql
      - redis

  nginx:
    build: .docker/nginx
    container_name: micro-videos-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/templates:/etc/nginx/templates
    environment:
      PHP_HOST: "app"
      PHP_PORT: "9000"
    networks:
      - codeflix-micro-videos
    depends_on:
      - app

  mysql:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    container_name: micro-videos-mysql
    restart: always
    tty: true
    ports:
      - "33060:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'code_micro_videos'
      MYSQL_ROOT_PASSWORD: '12345'
    networks:
      - codeflix-micro-videos

  redis:
     image: redis:alpine
     container_name: micro-videos-redis
     expose:
       - 6379
     networks:
       - codeflix-micro-videos

networks:
  codeflix-micro-videos:
    driver: bridge
